name: Build and test

on:
  workflow_dispatch:
    inputs:
      publish:
        type: boolean
        description: 'Upload rpms to github or not'
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Prepare
      shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get install rpm -y
    - name: Build
      shell: bash
      run: |
        rpmbuild --nodeps --build-in-place  --define "_topdir $PWD" --define "_sourcedir $PWD" --define "_builddir $PWD"  -bb rpm/jolla-chewing.spec
    - name: Create release
      if: ${{ fromJson(github.event.inputs.publish) }}
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -x
        assets=()
        for asset in RPMS/noarch/*.rpm; do
          assets+=("$asset")
          extracted_version=$(echo "$asset" | grep -P -o '[0-9]+\.[0-9]+-[0-9]+')
        done
        gh release create "$extracted_version" "${assets[@]}" --title "$extracted_version"
